window.LONGPUZZLEBENCH_PLAYGROUND = Object.freeze({
  totalEvaluationLevels: 114,
  games: Object.freeze([
    Object.freeze({
      slug: "maze-paint",
      runtimeId: "maze_paint",
      name: "Maze Paint",
      shortObjective: "Paint every open cell without choosing where the ball stops.",
      objective:
        "Cover every traversable cell. Each swipe sends the ball all the way to a wall or edge, so the order of turns determines what remains reachable.",
      interaction: "Swipe",
      controls: "Swipe up, down, left, or right anywhere on the board. The ball cannot stop midway.",
      controlIcon: "↔",
      challenge: "Approachable",
      preview: "../assets/games/maze_paint.webp",
      accent: "#2d6b8b",
      defaultLevel: "easy-1",
      levels: Object.freeze([
        Object.freeze({
          key: "easy-1",
          difficulty: "easy",
          level: 1,
          label: "Warm-up · Easy 1",
          evidence: "Verified optimum: 7 directional swipes",
          cardEvidence: "7 optimal swipes",
        }),
        Object.freeze({
          key: "hard-4",
          difficulty: "hard",
          level: 4,
          label: "Long route · Hard 4",
          evidence: "Verified optimum: 25 directional swipes",
          cardEvidence: "25 optimal swipes",
        }),
      ]),
    }),
    Object.freeze({
      slug: "bolt-unscrew",
      runtimeId: "bolt_unscrew",
      name: "Bolt Unscrew",
      shortObjective: "Move screws into exposed holes until every supported plank can fall.",
      objective:
        "Move each screw from a plank into an empty, uncovered hole. Planks obey gravity and can cover holes you were planning to use, making a legal early choice unrecoverable.",
      interaction: "Two taps",
      controls:
        "Tap a screw, then tap an uncovered empty hole. Tap the selected screw again to cancel. Clear every plank.",
      controlIcon: "⊙",
      challenge: "Irreversible",
      preview: "../assets/games/bolt_unscrew.webp",
      accent: "#a7442d",
      defaultLevel: "hard-1",
      levels: Object.freeze([
        Object.freeze({
          key: "easy-1",
          difficulty: "easy",
          level: 1,
          label: "First release · Easy 1",
          evidence: "1 plank · 1 screw transfer",
          cardEvidence: "One transfer",
        }),
        Object.freeze({
          key: "hard-1",
          difficulty: "hard",
          level: 1,
          label: "Hidden deadlock · Hard 1",
          evidence: "13 planks · 11 occupied screws · legal moves can destroy future access",
          cardEvidence: "Hidden deadlocks",
        }),
      ]),
    }),
    Object.freeze({
      slug: "rush-hour",
      runtimeId: "truck_escape_2",
      name: "Rush Hour",
      shortObjective: "Rearrange independently moving vehicles and drive the red target out.",
      objective:
        "Clear a continuous route for the red vehicle. Every vehicle keeps its own identity and can move only along its long axis without crossing another vehicle or fixed obstacle.",
      interaction: "Drag",
      controls:
        "Drag a vehicle along its long axis. Vehicles cannot turn, overlap, cross blockers, or leave the board except through the target exit.",
      controlIcon: "⇄",
      challenge: "Spatial",
      preview: "../assets/games/rush_hour_2.webp",
      accent: "#b56574",
      defaultLevel: "hard-6",
      levels: Object.freeze([
        Object.freeze({
          key: "easy-1",
          difficulty: "easy",
          level: 1,
          label: "Learn the axes · Easy 1",
          evidence: "Verified optimum: 4 vehicle drags",
          cardEvidence: "4 optimal drags",
        }),
        Object.freeze({
          key: "medium-3",
          difficulty: "medium",
          level: 3,
          label: "One car, not two · Medium 3",
          evidence: "Matched agent runs solve in 3 versus 6 actions after an object-identity split",
          cardEvidence: "Trajectory case",
        }),
        Object.freeze({
          key: "hard-6",
          difficulty: "hard",
          level: 6,
          label: "Move away first · Hard 6",
          evidence: "Verified optimum: 15 drags · the target must temporarily regress",
          cardEvidence: "15 optimal drags",
        }),
      ]),
    }),
    Object.freeze({
      slug: "nut-and-bolt",
      runtimeId: "nuts_bolts",
      name: "Nut and Bolt",
      shortObjective: "Sort colored nuts while preserving enough temporary workspace.",
      objective:
        "Group every color onto full, single-color bolts. A move transfers the entire same-color run at the source top, so spending an empty bolt too early can strand later colors.",
      interaction: "Two taps",
      controls:
        "Tap a source bolt, then a compatible target. The target must be empty or show the same color on top. Undo is available.",
      controlIcon: "↧",
      challenge: "Workspace",
      preview: "../assets/games/nut_and_bolt.webp",
      accent: "#76528d",
      defaultLevel: "hard-2",
      levels: Object.freeze([
        Object.freeze({
          key: "easy-1",
          difficulty: "easy",
          level: 1,
          label: "Learn the transfer · Easy 1",
          evidence: "8 nuts · 2 spare bolts",
          cardEvidence: "8 nuts",
        }),
        Object.freeze({
          key: "hard-2",
          difficulty: "hard",
          level: 2,
          label: "Preserve workspace · Hard 2",
          evidence: "56 nuts · a recorded successful agent attempt used 92 actions",
          cardEvidence: "Recorded: 92 actions",
        }),
      ]),
    }),
    Object.freeze({
      slug: "truck-escape",
      runtimeId: "truck_escape",
      name: "Truck Escape",
      shortObjective: "Remove every truck in an order that keeps each heading clear.",
      objective:
        "Click trucks whose forward swept path is clear. Removing one changes which paths intersect, creating a long dependency chain across individually simple choices.",
      interaction: "Tap",
      controls:
        "Tap a truck to send it straight forward. A blocked truck stays in place. Clear the whole field; no automatic hints are shown.",
      controlIcon: "↗",
      challenge: "Ordering",
      preview: "../assets/games/truck_escape.webp",
      accent: "#617d6d",
      defaultLevel: "default-1",
      levels: Object.freeze([
        Object.freeze({
          key: "default-1",
          difficulty: "default",
          level: 1,
          label: "Small yard · Level 1",
          evidence: "10 trucks · exactly 10 successful removals",
          cardEvidence: "10 trucks",
        }),
        Object.freeze({
          key: "default-5",
          difficulty: "default",
          level: 5,
          label: "Full yard · Level 5",
          evidence: "50 trucks · exactly 50 successful removals",
          cardEvidence: "50-truck chain",
        }),
      ]),
    }),
    Object.freeze({
      slug: "color-connect",
      runtimeId: "color_connect",
      name: "Color Connect",
      shortObjective: "Route every color pair through a board of shared, non-crossing space.",
      objective:
        "Connect every matching pair with orthogonal paths. Paths cannot overlap, cross, jump obstacles, or use another color's endpoint; a route that works now may consume a later color's only corridor.",
      interaction: "Click path",
      controls:
        "Click an endpoint, then each corner of its route, ending on the matching endpoint. Click a completed endpoint to redraw that color.",
      controlIcon: "⌁",
      challenge: "Shared space",
      preview: "../assets/games/color_connect.webp",
      accent: "#c3697f",
      defaultLevel: "hard-1",
      levels: Object.freeze([
        Object.freeze({
          key: "easy-4",
          difficulty: "easy",
          level: 4,
          label: "Four routes · Easy 4",
          evidence: "4 color pairs · 6 × 5 board",
          cardEvidence: "4 shared routes",
        }),
        Object.freeze({
          key: "hard-1",
          difficulty: "hard",
          level: 1,
          label: "Reserve the corridor · Hard 1",
          evidence: "8 color pairs · a recorded successful agent attempt used 33 actions",
          cardEvidence: "Recorded: 33 actions",
        }),
      ]),
    }),
  ]),
});
